controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_participate_event:
    path: '/event/{id}/participate'
    controller: 'App\Controller\EventController::participate'
