controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_participate_event:
    path: '/event/{id}/participate'
    controller: 'App\Controller\EventController::participate'

share_event:
    path: '/event/{id}/share'
    controller: 'App\Controller\EventController::shareEvent'
    methods: ['GET']


app_users:
    path: /user
    controller: App\Controller\UserController::index


withdraw_event:
    path: '/event/{id}/withdraw'
    controller: 'App\Controller\EventController::withdraw'
    methods: ['GET']

toggle_favorite:
    path: '/user/toggle_favorite/{id}'
    controller: 'App\Controller\UserController::toggleFavoriteProfile'

delete_user_profile:
    path: /user/delete
    controller: App\Controller\UserController::deleteProfile
    methods: ['POST']

# mes_favoris:
#     path: /mes-favoris
#     controller: App\Controller\FavorisController::mesFavoris
